foursquare:
  apiHost: https://api.foursquare.com/
  apiClientId: E4WJZ5EZL2FP3LOGJVCWMMQDJOYB02JKJIMZ20DRZHYR5ZOT
  apiClientSecret: J0RZKSNJZH1ZHEGS2R0YJ5EDT4DS4CHDNMCBHIETS53CJS4Y
  apiVersion: 20180403