foursquare:
  apiHost: https://api.foursquare.com/
  apiClientId: E4WJZ5EZL2FP3LOGJVCWMMQDJOYB02JKJIMZ20DRZHYR5ZOT
  apiClientSecret: J0RZKSNJZH1ZHEGS2R0YJ5EDT4DS4CHDNMCBHIETS53CJS4Y
  apiVersion: 20180403
logging:
  level:
    root: ${LOG_LVL:info}
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:foursquare}?useSSL=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
security:
  oauth2:
    resource:
      filter-order: ${FILTER_ORDER:3}