version: '2'
services:
  mysql:
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: hbstudent
      MYSQL_DATABASE: foursquare
    image: mysql:5.6
    ports:
      - 3308:3306
  service:
    container_name: service-container
    build:
      context: "."
    image: service-image:latest
    expose:
      - 8080
    ports:
      - 8080:8080
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql