foursquare:
  apiHost: https://api.foursquare.com/
  apiClientId: E4WJZ5EZL2FP3LOGJVCWMMQDJOYB02JKJIMZ20DRZHYR5ZOT
  apiClientSecret: J0RZKSNJZH1ZHEGS2R0YJ5EDT4DS4CHDNMCBHIETS53CJS4Y
  apiVersion: 20180403
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:foursquare}?useSSL=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${USERNAME:username}
    password: ${PASSWORD:password}
    properties:
      mail:
        smtp:
          auth: ${SMTP_AUTH:true}
          starttls:
            enable: ${STARTTLS:true}
cron:
  expression:
    weekly: 0 0 0 * * MON
    monthly:  0 0 0 1 * *